### ISSUE TITLE
Drafting colonists resets current outfit selection

### ISSUE THREAD

**Issue by frenchiveruti** [KiameV/rimworld-changedresser#20] opened 2017-11-26 03:37 UTC
Lets say I have 3 different outfits, worker, summer and winter clothing.  
If I have someone on "summer" and draft it, after I release him from his duty he'll reset his outfit to "worker" as he changed to "soldier" when he was drafted.

**Comment by KiameV** [comment] 2017-11-26 06:58
I just tried this out with a current save of mine.
I had a pawn with 4 outfits:
Not Combat
-Worker
-Naked (so it would be easy to identify)
Combat
-Heavy (power armor)
-Lights (jacket)

Test 1: Wearing Worker. Draft wearing Heavy. Un-draft and they were wearing worker apparel.
Test 2: Wearing Naked. Draft wearing Heavy. Un-draft and they were naked.
Test 3: Wearing Naked. Draft wearing Heavy. Switch to Light, wearing a jacket. Un-draft and they were naked,
Test 4: Switch to worker, wearing worker apparel. Draft and wearing jacket (Light). Switch to Heavy and wearing power armor. Un-draft wearing worker apparel.

Seems to be working as intended. Let me know if I'm not following the proper steps.

**Comment by frenchiveruti** [comment] 2017-11-26 18:19
@KiameV I saw what the problem was.
I was not using "Soldier" in the selection. It was only selected on the top row but not in the individual character rows.  
It works as intended but If I Draft a Pawn who doesn't have "soldier" in his rotation (let's say a non-violent pawn who sudendly decides to haul in the middle of a firefight). He will reset the outfit to the first one.  
In another words: If the pawn has something on "use for combat" but it doesn't have it on the personal selection, he will reset the outfit

**Comment by KiameV** [comment] 2017-11-26 20:51
Ah! Yep i am able to reproduce.
If a pawn has more than one non-combat outfit and they have used the other outfit, when they un-draft they switch to it. I think i know exactly how to fix this!

**Comment by KiameV** [comment] 2017-11-26 21:04
Fixed with the latest commit. Thanks for the help!

**Closed as completed by KiameV** 2017-11-26 21:04 UTC
